language: python

# Travis doesn't support 3.7 by default, but if we run it on xenial it works
matrix:
  fast_finish: true
  include:
  - python: 3.6
  - python: 3.7
    sudo: required
    dist: bionic
  - python: pypy3

install:
  - pip install . black coverage coveralls flake8 sphinx sphinx-argparse

script:
  - make flake
  - coverage run setup.py test
  - make -C docs doctest
  - make -C docs html

after_success:
  - coveralls

cache:
  pip: true
