language: python

# Travis doesn't support 3.7 by default, but if we run it on xenial it works
matrix:
  fast_finish: true
  include:
  - python: 3.6
    env: MATRIX=py36
  - python: 3.7
    sudo: required
    dist: bionic
    env: MATRIX=py37
  - python: pypy3
    env: MATRIX=pypy3

before_install:
  - if [ $MATRIX != pypy3 ]; then pip install black; fi
  - pip install coverage coveralls flake8 sphinx sphinx-argparse

install:
  - pip install .

script:
  - make flake
  - coverage run setup.py test
  - make -C docs doctest
  - make -C docs html

after_success:
  - coveralls

cache:
  pip: true
